import type { LandZoneData } from "./ground-risk";

export type GroundRegionGroupKey = "capital" | "gangwon" | "chungcheong" | "honam" | "yeongnam" | "jeju";
export type GroundTerrainType = "산악" | "도심" | "평야" | "해안 인접";

export type GroundZone = {
  id: string;
  label: string;
  name: string;
  sector: string;
  regionGroup: GroundRegionGroupKey;
  terrain: GroundTerrainType;
  center: [number, number];
  radius: number;
  data: LandZoneData;
};

function groundData(data: Partial<LandZoneData>): LandZoneData {
  return {
    temperatureC: 22,
    humidityPercent: 58,
    apparentTemperatureC: 24,
    wbgtC: 23,
    precipitationMm: 0,
    precipitationProbability: 20,
    windSpeedMs: 2.8,
    windDirection: "서",
    visibilityKm: 8,
    weatherStatus: "맑음",
    fogLevel: "없음",
    pm10Level: "보통",
    pm25Level: "보통",
    ozoneLevel: "보통",
    fireRiskLevel: "낮음",
    weatherAlert: "없음",
    pressureHpa: 1010,
    pressureTrend: "유지",
    uvIndexLevel: "보통",
    lightningRisk: "낮음",
    snowDepthCm: 0,
    icingRisk: "없음",
    ...data,
  };
}

const priorityGroundZones: GroundZone[] = [
  {
    id: "land-seosan",
    label: "서산",
    name: "서산시 기상 권역",
    sector: "충남 서해안 · 해안 인접",
    regionGroup: "chungcheong",
    terrain: "해안 인접",
    center: [36.784, 126.45],
    radius: 1400,
    data: groundData({
      temperatureC: 31,
      humidityPercent: 78,
      apparentTemperatureC: 35,
      wbgtC: 29,
      precipitationProbability: 20,
      windSpeedMs: 3.5,
      windDirection: "남서",
      visibilityKm: 4,
      fogLevel: "의심",
      pm25Level: "나쁨",
      fireRiskLevel: "높음",
      weatherAlert: "폭염주의보",
      pressureHpa: 1004,
      pressureTrend: "하강",
      uvIndexLevel: "높음",
    }),
  },
  {
    id: "land-dangjin",
    label: "당진",
    name: "당진시 기상 권역",
    sector: "충남 북부 · 해안 인접",
    regionGroup: "chungcheong",
    terrain: "해안 인접",
    center: [36.893, 126.629],
    radius: 1300,
    data: groundData({
      temperatureC: 26,
      humidityPercent: 72,
      apparentTemperatureC: 29,
      wbgtC: 26,
      precipitationProbability: 65,
      precipitationMm: 4,
      windSpeedMs: 6.2,
      windDirection: "서남서",
      visibilityKm: 5.5,
      weatherStatus: "흐림",
      fogLevel: "의심",
      pm10Level: "나쁨",
      fireRiskLevel: "보통",
      pressureTrend: "하강",
    }),
  },
  {
    id: "land-taean",
    label: "태안",
    name: "태안군 기상 권역",
    sector: "충남 서해안 · 평야/해안",
    regionGroup: "chungcheong",
    terrain: "해안 인접",
    center: [36.745, 126.298],
    radius: 1300,
    data: groundData({
      temperatureC: 19,
      humidityPercent: 52,
      apparentTemperatureC: 20,
      wbgtC: 21,
      precipitationProbability: 10,
      windSpeedMs: 2.4,
      windDirection: "북서",
      visibilityKm: 9.2,
      pm10Level: "좋음",
      pm25Level: "좋음",
      fireRiskLevel: "낮음",
      uvIndexLevel: "보통",
    }),
  },
  {
    id: "land-boryeong",
    label: "보령",
    name: "보령시 기상 권역",
    sector: "충남 남부 · 해안/산악",
    regionGroup: "chungcheong",
    terrain: "산악",
    center: [36.333, 126.612],
    radius: 1400,
    data: groundData({
      temperatureC: 28,
      humidityPercent: 80,
      apparentTemperatureC: 32,
      wbgtC: 28,
      precipitationProbability: 72,
      precipitationMm: 8,
      windSpeedMs: 7.8,
      windDirection: "남",
      visibilityKm: 3.2,
      weatherStatus: "비",
      fogLevel: "발생",
      pm25Level: "나쁨",
      fireRiskLevel: "보통",
      weatherAlert: "호우주의보",
      pressureHpa: 1000,
      pressureTrend: "급하강",
      lightningRisk: "주의",
    }),
  },
  {
    id: "land-cheorwon",
    label: "철원",
    name: "철원군 기상 권역",
    sector: "강원 북부 · 산악",
    regionGroup: "gangwon",
    terrain: "산악",
    center: [38.146, 127.313],
    radius: 1500,
    data: groundData({
      temperatureC: 33,
      humidityPercent: 84,
      apparentTemperatureC: 37,
      wbgtC: 30,
      precipitationProbability: 68,
      precipitationMm: 12,
      windSpeedMs: 8.5,
      windDirection: "남서",
      visibilityKm: 2.8,
      weatherStatus: "비",
      fogLevel: "발생",
      pm10Level: "나쁨",
      pm25Level: "나쁨",
      fireRiskLevel: "높음",
      weatherAlert: "폭염주의보",
      pressureHpa: 1002,
      pressureTrend: "하강",
      uvIndexLevel: "높음",
      lightningRisk: "주의",
    }),
  },
  {
    id: "land-paju",
    label: "파주",
    name: "파주시 기상 권역",
    sector: "수도권 북부 · 평야",
    regionGroup: "capital",
    terrain: "평야",
    center: [37.759, 126.78],
    radius: 1500,
    data: groundData({
      temperatureC: 24,
      humidityPercent: 82,
      apparentTemperatureC: 27,
      wbgtC: 25,
      precipitationProbability: 65,
      precipitationMm: 8,
      windSpeedMs: 6.4,
      visibilityKm: 5.8,
      weatherStatus: "흐림",
      fogLevel: "발생",
      pm10Level: "보통",
      fireRiskLevel: "보통",
      pressureTrend: "하강",
    }),
  },
  {
    id: "land-jeonju",
    label: "전주",
    name: "전주시 기상 권역",
    sector: "호남 내륙 · 도심",
    regionGroup: "honam",
    terrain: "도심",
    center: [35.824, 127.148],
    radius: 1300,
    data: groundData({
      temperatureC: 30,
      humidityPercent: 64,
      apparentTemperatureC: 32,
      wbgtC: 27,
      precipitationProbability: 30,
      windSpeedMs: 3.6,
      visibilityKm: 7.1,
      weatherStatus: "흐림",
      pm10Level: "보통",
      pm25Level: "보통",
      fireRiskLevel: "보통",
      uvIndexLevel: "높음",
    }),
  },
  {
    id: "land-pohang",
    label: "포항",
    name: "포항시 기상 권역",
    sector: "영남 동해안 · 해안 인접",
    regionGroup: "yeongnam",
    terrain: "해안 인접",
    center: [36.019, 129.343],
    radius: 1300,
    data: groundData({
      temperatureC: 18,
      humidityPercent: 88,
      apparentTemperatureC: 19,
      wbgtC: 21,
      precipitationProbability: 85,
      precipitationMm: 22,
      windSpeedMs: 9.8,
      visibilityKm: 2.2,
      weatherStatus: "비",
      fogLevel: "심함",
      pm10Level: "나쁨",
      pm25Level: "나쁨",
      fireRiskLevel: "낮음",
      weatherAlert: "호우주의보",
      pressureHpa: 996,
      pressureTrend: "급하강",
      lightningRisk: "가능",
    }),
  },
  {
    id: "land-jeju",
    label: "제주",
    name: "제주시 기상 권역",
    sector: "제주 북부 · 해안/산악",
    regionGroup: "jeju",
    terrain: "해안 인접",
    center: [33.499, 126.531],
    radius: 1400,
    data: groundData({
      temperatureC: 25,
      humidityPercent: 76,
      apparentTemperatureC: 28,
      wbgtC: 26,
      precipitationProbability: 55,
      precipitationMm: 3,
      windSpeedMs: 7.2,
      windDirection: "남동",
      visibilityKm: 6,
      weatherStatus: "흐림",
      fogLevel: "의심",
      fireRiskLevel: "낮음",
      pressureTrend: "유지",
    }),
  },
];

type GroundCitySeed = {
  id: string;
  label: string;
  name: string;
  sector: string;
  regionGroup: GroundRegionGroupKey;
  terrain: GroundTerrainType;
  center: [number, number];
  temperatureC: number;
  humidityPercent: number;
  precipitationProbability: number;
  windSpeedMs: number;
  visibilityKm: number;
};

const nationalGroundSeeds: GroundCitySeed[] = [
  { id: "land-seoul", label: "서울", name: "서울특별시 기상 권역", sector: "수도권 · 도심", regionGroup: "capital", terrain: "도심", center: [37.566, 126.978], temperatureC: 27, humidityPercent: 62, precipitationProbability: 30, windSpeedMs: 2.8, visibilityKm: 7.5 },
  { id: "land-busan", label: "부산", name: "부산광역시 기상 권역", sector: "영남 · 해안 도심", regionGroup: "yeongnam", terrain: "해안 인접", center: [35.179, 129.076], temperatureC: 25, humidityPercent: 70, precipitationProbability: 45, windSpeedMs: 5.4, visibilityKm: 6.8 },
  { id: "land-incheon", label: "인천", name: "인천광역시 기상 권역", sector: "수도권 · 서해안", regionGroup: "capital", terrain: "해안 인접", center: [37.456, 126.705], temperatureC: 24, humidityPercent: 76, precipitationProbability: 40, windSpeedMs: 5.8, visibilityKm: 5.6 },
  { id: "land-daegu", label: "대구", name: "대구광역시 기상 권역", sector: "영남 · 내륙분지", regionGroup: "yeongnam", terrain: "도심", center: [35.871, 128.601], temperatureC: 32, humidityPercent: 58, precipitationProbability: 20, windSpeedMs: 2.6, visibilityKm: 8.2 },
  { id: "land-daejeon", label: "대전", name: "대전광역시 기상 권역", sector: "충청 · 내륙 도심", regionGroup: "chungcheong", terrain: "도심", center: [36.35, 127.385], temperatureC: 29, humidityPercent: 64, precipitationProbability: 35, windSpeedMs: 3.2, visibilityKm: 7.2 },
  { id: "land-gwangju", label: "광주", name: "광주광역시 기상 권역", sector: "호남 · 내륙 도심", regionGroup: "honam", terrain: "도심", center: [35.159, 126.852], temperatureC: 30, humidityPercent: 66, precipitationProbability: 38, windSpeedMs: 3.0, visibilityKm: 7.0 },
  { id: "land-ulsan", label: "울산", name: "울산광역시 기상 권역", sector: "영남 · 동해안", regionGroup: "yeongnam", terrain: "해안 인접", center: [35.538, 129.311], temperatureC: 26, humidityPercent: 72, precipitationProbability: 42, windSpeedMs: 5.6, visibilityKm: 6.4 },
  { id: "land-sejong", label: "세종", name: "세종특별자치시 기상 권역", sector: "충청 · 내륙", regionGroup: "chungcheong", terrain: "평야", center: [36.48, 127.289], temperatureC: 28, humidityPercent: 60, precipitationProbability: 28, windSpeedMs: 2.8, visibilityKm: 8.0 },
  { id: "land-suwon", label: "수원", name: "경기도 수원시 기상 권역", sector: "수도권 · 남부 도심", regionGroup: "capital", terrain: "도심", center: [37.263, 127.028], temperatureC: 28, humidityPercent: 63, precipitationProbability: 32, windSpeedMs: 3.4, visibilityKm: 7.6 },
  { id: "land-chuncheon", label: "춘천", name: "강원도 춘천시 기상 권역", sector: "강원 · 내륙 산악", regionGroup: "gangwon", terrain: "산악", center: [37.881, 127.729], temperatureC: 26, humidityPercent: 68, precipitationProbability: 45, windSpeedMs: 3.8, visibilityKm: 6.2 },
  { id: "land-cheongju", label: "청주", name: "충청북도 청주시 기상 권역", sector: "충청 · 내륙 도심", regionGroup: "chungcheong", terrain: "도심", center: [36.642, 127.489], temperatureC: 29, humidityPercent: 61, precipitationProbability: 34, windSpeedMs: 3.1, visibilityKm: 7.7 },
  { id: "land-mokpo", label: "목포", name: "전라남도 목포시 기상 권역", sector: "호남 · 서남해안", regionGroup: "honam", terrain: "해안 인접", center: [34.811, 126.392], temperatureC: 24, humidityPercent: 78, precipitationProbability: 52, windSpeedMs: 6.0, visibilityKm: 5.2 },
  { id: "land-andong", label: "안동", name: "경상북도 안동시 기상 권역", sector: "영남 · 내륙 산악", regionGroup: "yeongnam", terrain: "산악", center: [36.568, 128.729], temperatureC: 27, humidityPercent: 58, precipitationProbability: 24, windSpeedMs: 2.9, visibilityKm: 8.4 },
  { id: "land-changwon", label: "창원", name: "경상남도 창원시 기상 권역", sector: "영남 · 남해안", regionGroup: "yeongnam", terrain: "해안 인접", center: [35.228, 128.681], temperatureC: 26, humidityPercent: 73, precipitationProbability: 44, windSpeedMs: 4.8, visibilityKm: 6.1 },
  { id: "land-gangneung", label: "강릉", name: "강원도 강릉시 기상 권역", sector: "강원 · 동해안", regionGroup: "gangwon", terrain: "해안 인접", center: [37.751, 128.876], temperatureC: 23, humidityPercent: 70, precipitationProbability: 42, windSpeedMs: 5.2, visibilityKm: 6.3 },
  { id: "land-goyang", label: "고양", name: "경기도 고양시 기상 권역", sector: "수도권 · 북서부 도심", regionGroup: "capital", terrain: "도심", center: [37.658, 126.832], temperatureC: 27, humidityPercent: 65, precipitationProbability: 34, windSpeedMs: 3.2, visibilityKm: 7.1 },
  { id: "land-yongin", label: "용인", name: "경기도 용인시 기상 권역", sector: "수도권 · 남동부", regionGroup: "capital", terrain: "평야", center: [37.242, 127.178], temperatureC: 28, humidityPercent: 61, precipitationProbability: 30, windSpeedMs: 3.1, visibilityKm: 7.8 },
  { id: "land-seongnam", label: "성남", name: "경기도 성남시 기상 권역", sector: "수도권 · 도심", regionGroup: "capital", terrain: "도심", center: [37.42, 127.126], temperatureC: 28, humidityPercent: 60, precipitationProbability: 32, windSpeedMs: 2.9, visibilityKm: 7.6 },
  { id: "land-hwaseong", label: "화성", name: "경기도 화성시 기상 권역", sector: "수도권 · 서해안", regionGroup: "capital", terrain: "해안 인접", center: [37.199, 126.831], temperatureC: 26, humidityPercent: 69, precipitationProbability: 38, windSpeedMs: 4.9, visibilityKm: 6.3 },
  { id: "land-wonju", label: "원주", name: "강원도 원주시 기상 권역", sector: "강원 · 내륙", regionGroup: "gangwon", terrain: "산악", center: [37.342, 127.92], temperatureC: 25, humidityPercent: 66, precipitationProbability: 44, windSpeedMs: 3.9, visibilityKm: 6.7 },
  { id: "land-sokcho", label: "속초", name: "강원도 속초시 기상 권역", sector: "강원 · 동해안", regionGroup: "gangwon", terrain: "해안 인접", center: [38.204, 128.591], temperatureC: 22, humidityPercent: 75, precipitationProbability: 48, windSpeedMs: 5.8, visibilityKm: 5.9 },
  { id: "land-taebaek", label: "태백", name: "강원도 태백시 기상 권역", sector: "강원 · 산악 고지", regionGroup: "gangwon", terrain: "산악", center: [37.164, 128.986], temperatureC: 18, humidityPercent: 72, precipitationProbability: 46, windSpeedMs: 6.2, visibilityKm: 5.6 },
  { id: "land-cheonan", label: "천안", name: "충청남도 천안시 기상 권역", sector: "충청 · 북부 내륙", regionGroup: "chungcheong", terrain: "도심", center: [36.815, 127.114], temperatureC: 29, humidityPercent: 63, precipitationProbability: 35, windSpeedMs: 3.4, visibilityKm: 7.4 },
  { id: "land-asan", label: "아산", name: "충청남도 아산시 기상 권역", sector: "충청 · 북부 평야", regionGroup: "chungcheong", terrain: "평야", center: [36.789, 127.002], temperatureC: 28, humidityPercent: 65, precipitationProbability: 36, windSpeedMs: 3.6, visibilityKm: 7.2 },
  { id: "land-gongju", label: "공주", name: "충청남도 공주시 기상 권역", sector: "충청 · 내륙", regionGroup: "chungcheong", terrain: "평야", center: [36.446, 127.119], temperatureC: 29, humidityPercent: 60, precipitationProbability: 32, windSpeedMs: 3.0, visibilityKm: 8.1 },
  { id: "land-nonsan", label: "논산", name: "충청남도 논산시 기상 권역", sector: "충청 · 남부 평야", regionGroup: "chungcheong", terrain: "평야", center: [36.187, 127.098], temperatureC: 30, humidityPercent: 62, precipitationProbability: 34, windSpeedMs: 3.3, visibilityKm: 7.8 },
  { id: "land-chungju", label: "충주", name: "충청북도 충주시 기상 권역", sector: "충청 · 내륙 산지", regionGroup: "chungcheong", terrain: "산악", center: [36.991, 127.926], temperatureC: 27, humidityPercent: 64, precipitationProbability: 39, windSpeedMs: 3.7, visibilityKm: 7.0 },
  { id: "land-gunsan", label: "군산", name: "전라북도 군산시 기상 권역", sector: "호남 · 서해안", regionGroup: "honam", terrain: "해안 인접", center: [35.967, 126.736], temperatureC: 25, humidityPercent: 76, precipitationProbability: 50, windSpeedMs: 5.9, visibilityKm: 5.4 },
  { id: "land-iksan", label: "익산", name: "전라북도 익산시 기상 권역", sector: "호남 · 내륙 평야", regionGroup: "honam", terrain: "평야", center: [35.948, 126.957], temperatureC: 29, humidityPercent: 65, precipitationProbability: 38, windSpeedMs: 3.2, visibilityKm: 7.2 },
  { id: "land-suncheon", label: "순천", name: "전라남도 순천시 기상 권역", sector: "호남 · 남해 내륙", regionGroup: "honam", terrain: "평야", center: [34.95, 127.487], temperatureC: 27, humidityPercent: 74, precipitationProbability: 46, windSpeedMs: 4.2, visibilityKm: 6.2 },
  { id: "land-yeosu", label: "여수", name: "전라남도 여수시 기상 권역", sector: "호남 · 남해안", regionGroup: "honam", terrain: "해안 인접", center: [34.76, 127.662], temperatureC: 25, humidityPercent: 78, precipitationProbability: 52, windSpeedMs: 6.6, visibilityKm: 5.3 },
  { id: "land-haenam", label: "해남", name: "전라남도 해남군 기상 권역", sector: "호남 · 서남해안", regionGroup: "honam", terrain: "해안 인접", center: [34.573, 126.599], temperatureC: 24, humidityPercent: 79, precipitationProbability: 54, windSpeedMs: 5.7, visibilityKm: 5.0 },
  { id: "land-gyeongju", label: "경주", name: "경상북도 경주시 기상 권역", sector: "영남 · 동해 내륙", regionGroup: "yeongnam", terrain: "평야", center: [35.856, 129.224], temperatureC: 27, humidityPercent: 63, precipitationProbability: 34, windSpeedMs: 3.8, visibilityKm: 7.5 },
  { id: "land-gumi", label: "구미", name: "경상북도 구미시 기상 권역", sector: "영남 · 내륙 산업권", regionGroup: "yeongnam", terrain: "도심", center: [36.119, 128.344], temperatureC: 29, humidityPercent: 59, precipitationProbability: 30, windSpeedMs: 3.0, visibilityKm: 8.0 },
  { id: "land-jinju", label: "진주", name: "경상남도 진주시 기상 권역", sector: "영남 · 남부 내륙", regionGroup: "yeongnam", terrain: "평야", center: [35.18, 128.108], temperatureC: 28, humidityPercent: 67, precipitationProbability: 40, windSpeedMs: 3.6, visibilityKm: 6.9 },
  { id: "land-geoje", label: "거제", name: "경상남도 거제시 기상 권역", sector: "영남 · 남해안", regionGroup: "yeongnam", terrain: "해안 인접", center: [34.88, 128.621], temperatureC: 25, humidityPercent: 77, precipitationProbability: 48, windSpeedMs: 6.2, visibilityKm: 5.8 },
  { id: "land-seogwipo", label: "서귀포", name: "제주도 서귀포시 기상 권역", sector: "제주 남부 · 해안/산악", regionGroup: "jeju", terrain: "해안 인접", center: [33.254, 126.56], temperatureC: 25, humidityPercent: 78, precipitationProbability: 58, windSpeedMs: 6.4, visibilityKm: 5.7 },
  { id: "land-gangnam", label: "강남", name: "서울특별시 강남구 기상 권역", sector: "수도권 · 서울 동남권", regionGroup: "capital", terrain: "도심", center: [37.518, 127.047], temperatureC: 28, humidityPercent: 61, precipitationProbability: 30, windSpeedMs: 2.7, visibilityKm: 7.4 },
  { id: "land-jongno", label: "종로", name: "서울특별시 종로구 기상 권역", sector: "수도권 · 서울 도심", regionGroup: "capital", terrain: "도심", center: [37.573, 126.979], temperatureC: 27, humidityPercent: 63, precipitationProbability: 32, windSpeedMs: 2.6, visibilityKm: 7.2 },
  { id: "land-nowon", label: "노원", name: "서울특별시 노원구 기상 권역", sector: "수도권 · 서울 북부", regionGroup: "capital", terrain: "도심", center: [37.654, 127.056], temperatureC: 27, humidityPercent: 64, precipitationProbability: 34, windSpeedMs: 2.8, visibilityKm: 7.0 },
  { id: "land-songpa", label: "송파", name: "서울특별시 송파구 기상 권역", sector: "수도권 · 서울 동부", regionGroup: "capital", terrain: "도심", center: [37.514, 127.106], temperatureC: 28, humidityPercent: 62, precipitationProbability: 31, windSpeedMs: 2.9, visibilityKm: 7.3 },
  { id: "land-dong-gu-daejeon", label: "대전 동구", name: "대전광역시 동구 기상 권역", sector: "충청 · 대전 동부", regionGroup: "chungcheong", terrain: "도심", center: [36.312, 127.454], temperatureC: 29, humidityPercent: 64, precipitationProbability: 35, windSpeedMs: 3.1, visibilityKm: 7.0 },
  { id: "land-yuseong", label: "유성", name: "대전광역시 유성구 기상 권역", sector: "충청 · 대전 서북부", regionGroup: "chungcheong", terrain: "도심", center: [36.362, 127.356], temperatureC: 29, humidityPercent: 63, precipitationProbability: 34, windSpeedMs: 3.0, visibilityKm: 7.4 },
  { id: "land-seosan-dae-san", label: "대산", name: "서산시 대산읍 기상 권역", sector: "충남 서해안 · 대산", regionGroup: "chungcheong", terrain: "해안 인접", center: [37.007, 126.391], temperatureC: 25, humidityPercent: 75, precipitationProbability: 42, windSpeedMs: 5.2, visibilityKm: 5.8 },
  { id: "land-seosan-haemi", label: "해미", name: "서산시 해미면 기상 권역", sector: "충남 내륙 · 해미", regionGroup: "chungcheong", terrain: "평야", center: [36.713, 126.543], temperatureC: 27, humidityPercent: 67, precipitationProbability: 36, windSpeedMs: 3.5, visibilityKm: 7.2 },
  { id: "land-buk-gu-gwangju", label: "광주 북구", name: "광주광역시 북구 기상 권역", sector: "호남 · 광주 북부", regionGroup: "honam", terrain: "도심", center: [35.174, 126.911], temperatureC: 30, humidityPercent: 66, precipitationProbability: 38, windSpeedMs: 3.0, visibilityKm: 7.1 },
  { id: "land-haeundae", label: "해운대", name: "부산광역시 해운대구 기상 권역", sector: "영남 · 부산 동부 해안", regionGroup: "yeongnam", terrain: "해안 인접", center: [35.163, 129.163], temperatureC: 25, humidityPercent: 72, precipitationProbability: 44, windSpeedMs: 5.5, visibilityKm: 6.6 },
  { id: "land-jeju-aewol", label: "애월", name: "제주시 애월읍 기상 권역", sector: "제주 북서부 · 해안", regionGroup: "jeju", terrain: "해안 인접", center: [33.464, 126.318], temperatureC: 25, humidityPercent: 78, precipitationProbability: 58, windSpeedMs: 6.7, visibilityKm: 5.8 },
];

const additionalGroundSeeds: GroundCitySeed[] = [
  { id: "land-uijeongbu", label: "의정부", name: "경기도 의정부시 기상 권역", sector: "수도권 · 북부 도심", regionGroup: "capital", terrain: "도심", center: [37.739, 127.034], temperatureC: 27, humidityPercent: 64, precipitationProbability: 34, windSpeedMs: 3.0, visibilityKm: 7.1 },
  { id: "land-bucheon", label: "부천", name: "경기도 부천시 기상 권역", sector: "수도권 · 서부 도심", regionGroup: "capital", terrain: "도심", center: [37.503, 126.766], temperatureC: 28, humidityPercent: 63, precipitationProbability: 33, windSpeedMs: 3.1, visibilityKm: 7.0 },
  { id: "land-anyang", label: "안양", name: "경기도 안양시 기상 권역", sector: "수도권 · 남부 도심", regionGroup: "capital", terrain: "도심", center: [37.394, 126.957], temperatureC: 28, humidityPercent: 62, precipitationProbability: 32, windSpeedMs: 3.0, visibilityKm: 7.2 },
  { id: "land-pyeongtaek", label: "평택", name: "경기도 평택시 기상 권역", sector: "수도권 · 서해 평야", regionGroup: "capital", terrain: "평야", center: [36.992, 127.112], temperatureC: 28, humidityPercent: 66, precipitationProbability: 36, windSpeedMs: 4.1, visibilityKm: 6.8 },
  { id: "land-ansan", label: "안산", name: "경기도 안산시 기상 권역", sector: "수도권 · 서해안 도심", regionGroup: "capital", terrain: "해안 인접", center: [37.322, 126.831], temperatureC: 27, humidityPercent: 68, precipitationProbability: 38, windSpeedMs: 4.8, visibilityKm: 6.2 },
  { id: "land-gimpo", label: "김포", name: "경기도 김포시 기상 권역", sector: "수도권 · 한강 하구", regionGroup: "capital", terrain: "평야", center: [37.616, 126.716], temperatureC: 26, humidityPercent: 70, precipitationProbability: 39, windSpeedMs: 4.5, visibilityKm: 6.0 },
  { id: "land-hongcheon", label: "홍천", name: "강원도 홍천군 기상 권역", sector: "강원 · 내륙 산지", regionGroup: "gangwon", terrain: "산악", center: [37.697, 127.888], temperatureC: 25, humidityPercent: 67, precipitationProbability: 42, windSpeedMs: 3.9, visibilityKm: 6.8 },
  { id: "land-pyeongchang", label: "평창", name: "강원도 평창군 기상 권역", sector: "강원 · 고원 산악", regionGroup: "gangwon", terrain: "산악", center: [37.37, 128.39], temperatureC: 21, humidityPercent: 72, precipitationProbability: 46, windSpeedMs: 5.1, visibilityKm: 6.1 },
  { id: "land-inje", label: "인제", name: "강원도 인제군 기상 권역", sector: "강원 · 북부 산악", regionGroup: "gangwon", terrain: "산악", center: [38.07, 128.17], temperatureC: 22, humidityPercent: 73, precipitationProbability: 47, windSpeedMs: 5.4, visibilityKm: 5.9 },
  { id: "land-donghae", label: "동해", name: "강원도 동해시 기상 권역", sector: "강원 · 동해안", regionGroup: "gangwon", terrain: "해안 인접", center: [37.525, 129.114], temperatureC: 23, humidityPercent: 72, precipitationProbability: 45, windSpeedMs: 6.0, visibilityKm: 6.0 },
  { id: "land-samcheok", label: "삼척", name: "강원도 삼척시 기상 권역", sector: "강원 · 동남 해안", regionGroup: "gangwon", terrain: "해안 인접", center: [37.45, 129.17], temperatureC: 23, humidityPercent: 71, precipitationProbability: 44, windSpeedMs: 5.9, visibilityKm: 6.2 },
  { id: "land-hongseong", label: "홍성", name: "충청남도 홍성군 기상 권역", sector: "충청 · 서해 내륙", regionGroup: "chungcheong", terrain: "평야", center: [36.601, 126.661], temperatureC: 28, humidityPercent: 66, precipitationProbability: 37, windSpeedMs: 3.9, visibilityKm: 7.0 },
  { id: "land-yesan", label: "예산", name: "충청남도 예산군 기상 권역", sector: "충청 · 예당 평야", regionGroup: "chungcheong", terrain: "평야", center: [36.682, 126.849], temperatureC: 28, humidityPercent: 65, precipitationProbability: 36, windSpeedMs: 3.6, visibilityKm: 7.2 },
  { id: "land-seocheon", label: "서천", name: "충청남도 서천군 기상 권역", sector: "충청 · 남부 서해안", regionGroup: "chungcheong", terrain: "해안 인접", center: [36.08, 126.691], temperatureC: 26, humidityPercent: 74, precipitationProbability: 48, windSpeedMs: 5.4, visibilityKm: 5.7 },
  { id: "land-buyeo", label: "부여", name: "충청남도 부여군 기상 권역", sector: "충청 · 금강 내륙", regionGroup: "chungcheong", terrain: "평야", center: [36.276, 126.91], temperatureC: 29, humidityPercent: 65, precipitationProbability: 38, windSpeedMs: 3.3, visibilityKm: 7.4 },
  { id: "land-jecheon", label: "제천", name: "충청북도 제천시 기상 권역", sector: "충청 · 북부 산지", regionGroup: "chungcheong", terrain: "산악", center: [37.132, 128.191], temperatureC: 25, humidityPercent: 67, precipitationProbability: 42, windSpeedMs: 4.2, visibilityKm: 6.8 },
  { id: "land-eumseong", label: "음성", name: "충청북도 음성군 기상 권역", sector: "충청 · 중부 내륙", regionGroup: "chungcheong", terrain: "평야", center: [36.94, 127.69], temperatureC: 27, humidityPercent: 63, precipitationProbability: 36, windSpeedMs: 3.4, visibilityKm: 7.3 },
  { id: "land-jeongeup", label: "정읍", name: "전라북도 정읍시 기상 권역", sector: "호남 · 내륙 평야", regionGroup: "honam", terrain: "평야", center: [35.569, 126.856], temperatureC: 29, humidityPercent: 66, precipitationProbability: 40, windSpeedMs: 3.5, visibilityKm: 7.0 },
  { id: "land-namwon", label: "남원", name: "전라북도 남원시 기상 권역", sector: "호남 · 지리산 내륙", regionGroup: "honam", terrain: "산악", center: [35.416, 127.39], temperatureC: 28, humidityPercent: 68, precipitationProbability: 44, windSpeedMs: 3.7, visibilityKm: 6.7 },
  { id: "land-buan", label: "부안", name: "전라북도 부안군 기상 권역", sector: "호남 · 서해안", regionGroup: "honam", terrain: "해안 인접", center: [35.731, 126.733], temperatureC: 26, humidityPercent: 75, precipitationProbability: 50, windSpeedMs: 5.6, visibilityKm: 5.4 },
  { id: "land-naju", label: "나주", name: "전라남도 나주시 기상 권역", sector: "호남 · 영산강 평야", regionGroup: "honam", terrain: "평야", center: [35.016, 126.711], temperatureC: 30, humidityPercent: 67, precipitationProbability: 40, windSpeedMs: 3.2, visibilityKm: 7.0 },
  { id: "land-gwangyang", label: "광양", name: "전라남도 광양시 기상 권역", sector: "호남 · 남해 산업권", regionGroup: "honam", terrain: "해안 인접", center: [34.94, 127.695], temperatureC: 27, humidityPercent: 75, precipitationProbability: 48, windSpeedMs: 5.8, visibilityKm: 5.8 },
  { id: "land-wando", label: "완도", name: "전라남도 완도군 기상 권역", sector: "호남 · 남해 도서", regionGroup: "honam", terrain: "해안 인접", center: [34.311, 126.755], temperatureC: 25, humidityPercent: 80, precipitationProbability: 56, windSpeedMs: 6.4, visibilityKm: 5.2 },
  { id: "land-yeongju", label: "영주", name: "경상북도 영주시 기상 권역", sector: "영남 · 북부 산지", regionGroup: "yeongnam", terrain: "산악", center: [36.805, 128.624], temperatureC: 26, humidityPercent: 61, precipitationProbability: 32, windSpeedMs: 3.6, visibilityKm: 7.6 },
  { id: "land-sangju", label: "상주", name: "경상북도 상주시 기상 권역", sector: "영남 · 내륙 평야", regionGroup: "yeongnam", terrain: "평야", center: [36.411, 128.159], temperatureC: 28, humidityPercent: 60, precipitationProbability: 30, windSpeedMs: 3.2, visibilityKm: 8.0 },
  { id: "land-gimcheon", label: "김천", name: "경상북도 김천시 기상 권역", sector: "영남 · 내륙 교통축", regionGroup: "yeongnam", terrain: "평야", center: [36.139, 128.113], temperatureC: 29, humidityPercent: 60, precipitationProbability: 30, windSpeedMs: 3.0, visibilityKm: 8.0 },
  { id: "land-gyeongsan", label: "경산", name: "경상북도 경산시 기상 권역", sector: "영남 · 대구권", regionGroup: "yeongnam", terrain: "도심", center: [35.825, 128.742], temperatureC: 31, humidityPercent: 59, precipitationProbability: 28, windSpeedMs: 2.8, visibilityKm: 8.1 },
  { id: "land-miryang", label: "밀양", name: "경상남도 밀양시 기상 권역", sector: "영남 · 내륙 분지", regionGroup: "yeongnam", terrain: "평야", center: [35.503, 128.746], temperatureC: 30, humidityPercent: 64, precipitationProbability: 36, windSpeedMs: 3.4, visibilityKm: 7.2 },
  { id: "land-tongyeong", label: "통영", name: "경상남도 통영시 기상 권역", sector: "영남 · 남해 도서", regionGroup: "yeongnam", terrain: "해안 인접", center: [34.854, 128.433], temperatureC: 25, humidityPercent: 78, precipitationProbability: 50, windSpeedMs: 6.3, visibilityKm: 5.6 },
  { id: "land-yangsan", label: "양산", name: "경상남도 양산시 기상 권역", sector: "영남 · 부산 북부", regionGroup: "yeongnam", terrain: "도심", center: [35.335, 129.037], temperatureC: 27, humidityPercent: 70, precipitationProbability: 42, windSpeedMs: 4.8, visibilityKm: 6.5 },
  { id: "land-jeju-seongsan", label: "성산", name: "제주도 성산읍 기상 권역", sector: "제주 동부 · 해안", regionGroup: "jeju", terrain: "해안 인접", center: [33.39, 126.88], temperatureC: 25, humidityPercent: 79, precipitationProbability: 58, windSpeedMs: 6.5, visibilityKm: 5.6 },
  { id: "land-jeju-hallim", label: "한림", name: "제주시 한림읍 기상 권역", sector: "제주 서부 · 해안", regionGroup: "jeju", terrain: "해안 인접", center: [33.41, 126.27], temperatureC: 25, humidityPercent: 78, precipitationProbability: 56, windSpeedMs: 6.3, visibilityKm: 5.8 },
];

const mergedNationalGroundSeeds = [...nationalGroundSeeds, ...additionalGroundSeeds];

const nationalGroundZones: GroundZone[] = mergedNationalGroundSeeds.map((seed) => ({
  id: seed.id,
  label: seed.label,
  name: seed.name,
  sector: seed.sector,
  regionGroup: seed.regionGroup,
  terrain: seed.terrain,
  center: seed.center,
  radius: 1300,
  data: groundData({
    temperatureC: seed.temperatureC,
    humidityPercent: seed.humidityPercent,
    apparentTemperatureC: seed.temperatureC + (seed.humidityPercent >= 70 ? 3 : 1),
    wbgtC: seed.temperatureC >= 30 ? 28 : 24,
    precipitationProbability: seed.precipitationProbability,
    precipitationMm: seed.precipitationProbability >= 50 ? 3 : 0,
    windSpeedMs: seed.windSpeedMs,
    visibilityKm: seed.visibilityKm,
    weatherStatus: seed.precipitationProbability >= 50 ? "비" : seed.precipitationProbability >= 35 ? "흐림" : "맑음",
    fogLevel: seed.visibilityKm <= 5.5 ? "의심" : "없음",
    fireRiskLevel: seed.temperatureC >= 30 && seed.humidityPercent < 65 ? "높음" : "보통",
    pressureTrend: seed.precipitationProbability >= 45 ? "하강" : "유지",
  }),
}));

export const groundZones: GroundZone[] = [...priorityGroundZones, ...nationalGroundZones];
